export const products = [
  {
    id: "iphone-13-pro-128gb",
    name: "iPhone 13 Pro",
    brand: "Apple",
    model: "iPhone 13 Pro",
    price: 649.99,
    discount: 15,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used iPhone 13 Pro in excellent condition. Features a 6.1-inch Super Retina XDR display with ProMotion technology, A15 Bionic chip, and a pro camera system. Minor wear on the frame but screen is in perfect condition.",
    condition: "Excellent",
    storage: "128GB",
    color: "Graphite",
    warranty: "90 days",
    stock: 15,
    rating: 4.7,
    reviews: 128,
    batteryHealth: 89,
    ram: "6GB",
    display: "6.1-inch Super Retina XDR",
    processor: "A15 Bionic",
    camera: "12MP Triple Camera",
    battery: "3095 mAh",
    os: "iOS 16",
    connectivity: "5G, Wi-Fi 6, Bluetooth 5.0",
  },
  {
    id: "samsung-galaxy-s21-256gb",
    name: "Samsung Galaxy S21",
    brand: "Samsung",
    model: "Galaxy S21",
    price: 499.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used Samsung Galaxy S21 in good condition. Features a 6.2-inch Dynamic AMOLED 2X display, Exynos 2100 processor, and a versatile triple camera system. Some light scratches on the back panel but fully functional.",
    condition: "Good",
    storage: "256GB",
    color: "Phantom Gray",
    warranty: "60 days",
    stock: 8,
    rating: 4.5,
    reviews: 92,
    batteryHealth: 85,
    ram: "8GB",
    display: "6.2-inch Dynamic AMOLED 2X",
    processor: "Exynos 2100",
    camera: "12MP Triple Camera",
    battery: "4000 mAh",
    os: "Android 13",
    connectivity: "5G, Wi-Fi 6, Bluetooth 5.0",
  },
  {
    id: "google-pixel-6-pro-128gb",
    name: "Google Pixel 6 Pro",
    brand: "Google",
    model: "Pixel 6 Pro",
    price: 549.99,
    discount: 10,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used Google Pixel 6 Pro in very good condition. Features a 6.7-inch LTPO AMOLED display, Google Tensor chip, and an advanced camera system with 4x optical zoom. Minor wear on corners but screen is flawless.",
    condition: "Very Good",
    storage: "128GB",
    color: "Stormy Black",
    warranty: "90 days",
    stock: 6,
    rating: 4.6,
    reviews: 78,
    batteryHealth: 92,
    ram: "12GB",
    display: "6.7-inch LTPO AMOLED",
    processor: "Google Tensor",
    camera: "50MP Triple Camera",
    battery: "5003 mAh",
    os: "Android 13",
    connectivity: "5G, Wi-Fi 6E, Bluetooth 5.2",
  },
  {
    id: "iphone-12-64gb",
    name: "iPhone 12",
    brand: "Apple",
    model: "iPhone 12",
    price: 429.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used iPhone 12 in good condition. Features a 6.1-inch Super Retina XDR display, A14 Bionic chip, and a dual camera system. Some visible scratches on the frame and back glass but fully functional.",
    condition: "Good",
    storage: "64GB",
    color: "Blue",
    warranty: "60 days",
    stock: 12,
    rating: 4.4,
    reviews: 105,
    batteryHealth: 84,
    ram: "4GB",
    display: "6.1-inch Super Retina XDR",
    processor: "A14 Bionic",
    camera: "12MP Dual Camera",
    battery: "2815 mAh",
    os: "iOS 16",
    connectivity: "5G, Wi-Fi 6, Bluetooth 5.0",
  },
  {
    id: "oneplus-9-pro-256gb",
    name: "OnePlus 9 Pro",
    brand: "OnePlus",
    model: "9 Pro",
    price: 479.99,
    discount: 20,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used OnePlus 9 Pro in very good condition. Features a 6.7-inch Fluid AMOLED display with LTPO, Snapdragon 888 processor, and Hasselblad camera system. Minor wear on the frame but screen is in excellent condition.",
    condition: "Very Good",
    storage: "256GB",
    color: "Morning Mist",
    warranty: "90 days",
    stock: 5,
    rating: 4.5,
    reviews: 67,
    batteryHealth: 88,
    ram: "12GB",
    display: "6.7-inch Fluid AMOLED with LTPO",
    processor: "Snapdragon 888",
    camera: "48MP Quad Camera",
    battery: "4500 mAh",
    os: "OxygenOS (Android 13)",
    connectivity: "5G, Wi-Fi 6, Bluetooth 5.2",
  },
  {
    id: "xiaomi-mi-11-256gb",
    name: "Xiaomi Mi 11",
    brand: "Xiaomi",
    model: "Mi 11",
    price: 399.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used Xiaomi Mi 11 in good condition. Features a 6.81-inch AMOLED display, Snapdragon 888 processor, and a 108MP main camera. Some light scratches on the back panel but fully functional.",
    condition: "Good",
    storage: "256GB",
    color: "Midnight Gray",
    warranty: "60 days",
    stock: 7,
    rating: 4.3,
    reviews: 54,
    batteryHealth: 86,
    ram: "8GB",
    display: "6.81-inch AMOLED",
    processor: "Snapdragon 888",
    camera: "108MP Triple Camera",
    battery: "4600 mAh",
    os: "MIUI (Android 12)",
    connectivity: "5G, Wi-Fi 6, Bluetooth 5.2",
  },
  {
    id: "samsung-galaxy-note-20-ultra-256gb",
    name: "Samsung Galaxy Note 20 Ultra",
    brand: "Samsung",
    model: "Galaxy Note 20 Ultra",
    price: 599.99,
    discount: 5,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used Samsung Galaxy Note 20 Ultra in excellent condition. Features a 6.9-inch Dynamic AMOLED 2X display, Exynos 990 processor, and a versatile triple camera system with 5x optical zoom. Minor wear on corners but screen is flawless.",
    condition: "Excellent",
    storage: "256GB",
    color: "Mystic Bronze",
    warranty: "90 days",
    stock: 4,
    rating: 4.7,
    reviews: 89,
    batteryHealth: 90,
    ram: "12GB",
    display: "6.9-inch Dynamic AMOLED 2X",
    processor: "Exynos 990",
    camera: "108MP Triple Camera",
    battery: "4500 mAh",
    os: "Android 13",
    connectivity: "5G, Wi-Fi 6, Bluetooth 5.0",
  },
  {
    id: "iphone-se-2022-128gb",
    name: "iPhone SE (2022)",
    brand: "Apple",
    model: "iPhone SE (3rd gen)",
    price: 299.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used iPhone SE (2022) in very good condition. Features a 4.7-inch Retina HD display, A15 Bionic chip, and a 12MP camera. Some light scratches on the frame but screen is in excellent condition.",
    condition: "Very Good",
    storage: "128GB",
    color: "Midnight",
    warranty: "60 days",
    stock: 10,
    rating: 4.4,
    reviews: 72,
    batteryHealth: 93,
    ram: "4GB",
    display: "4.7-inch Retina HD",
    processor: "A15 Bionic",
    camera: "12MP Single Camera",
    battery: "2018 mAh",
    os: "iOS 16",
    connectivity: "5G, Wi-Fi 6, Bluetooth 5.0",
  },
  {
    id: "google-pixel-5a-128gb",
    name: "Google Pixel 5a",
    brand: "Google",
    model: "Pixel 5a",
    price: 279.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used Google Pixel 5a in good condition. Features a 6.34-inch OLED display, Snapdragon 765G processor, and a dual camera system. Some visible scratches on the back but fully functional.",
    condition: "Good",
    storage: "128GB",
    color: "Mostly Black",
    warranty: "60 days",
    stock: 8,
    rating: 4.3,
    reviews: 61,
    batteryHealth: 87,
    ram: "6GB",
    display: "6.34-inch OLED",
    processor: "Snapdragon 765G",
    camera: "12.2MP Dual Camera",
    battery: "4680 mAh",
    os: "Android 13",
    connectivity: "5G, Wi-Fi 5, Bluetooth 5.0",
  },
  {
    id: "iphone-14-pro-max-256gb",
    name: "iPhone 14 Pro Max",
    brand: "Apple",
    model: "iPhone 14 Pro Max",
    price: 899.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used iPhone 14 Pro Max in like new condition. Features a 6.7-inch Super Retina XDR display with ProMotion technology, A16 Bionic chip, and an advanced camera system. Minimal signs of use, looks and works like new.",
    condition: "Like New",
    storage: "256GB",
    color: "Deep Purple",
    warranty: "6 months",
    stock: 3,
    rating: 4.9,
    reviews: 42,
    batteryHealth: 97,
    ram: "6GB",
    display: "6.7-inch Super Retina XDR",
    processor: "A16 Bionic",
    camera: "48MP Triple Camera",
    battery: "4323 mAh",
    os: "iOS 16",
    connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
  },
  {
    id: "samsung-galaxy-s22-ultra-256gb",
    name: "Samsung Galaxy S22 Ultra",
    brand: "Samsung",
    model: "Galaxy S22 Ultra",
    price: 799.99,
    discount: 10,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used Samsung Galaxy S22 Ultra in excellent condition. Features a 6.8-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 1 processor, and a versatile quad camera system with 10x optical zoom. Minor wear on the frame but screen is flawless.",
    condition: "Excellent",
    storage: "256GB",
    color: "Phantom Black",
    warranty: "90 days",
    stock: 5,
    rating: 4.8,
    reviews: 76,
    batteryHealth: 92,
    ram: "12GB",
    display: "6.8-inch Dynamic AMOLED 2X",
    processor: "Snapdragon 8 Gen 1",
    camera: "108MP Quad Camera",
    battery: "5000 mAh",
    os: "Android 13",
    connectivity: "5G, Wi-Fi 6E, Bluetooth 5.2",
  },
  {
    id: "motorola-edge-30-pro-128gb",
    name: "Motorola Edge 30 Pro",
    brand: "Motorola",
    model: "Edge 30 Pro",
    price: 349.99,
    discount: 15,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Used Motorola Edge 30 Pro in good condition. Features a 6.7-inch OLED display, Snapdragon 8 Gen 1 processor, and a 50MP main camera. Some light scratches on the back panel but fully functional.",
    condition: "Good",
    storage: "128GB",
    color: "Cosmos Blue",
    warranty: "60 days",
    stock: 6,
    rating: 4.2,
    reviews: 48,
    batteryHealth: 85,
    ram: "8GB",
    display: "6.7-inch OLED",
    processor: "Snapdragon 8 Gen 1",
    camera: "50MP Triple Camera",
    battery: "4800 mAh",
    os: "Android 12",
    connectivity: "5G, Wi-Fi 6E, Bluetooth 5.2",
  },
];
