version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: aldngrha
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    environment:
      DATABASE_URL: postgresql://aldngrha:mysecretpassword@postgres:5432/mydb
      JWT_SECRET: supersecretkey
    depends_on:
      - postgres
volumes:
  pgdata:
